services:
  teaspeak:
    build: .
    ports:
      - "9987:9987/tcp"
      - "9987:9987/udp"
      - "10101:10101"
      - "30303:30303"
    volumes:
      - teaspeak_data:/teaspeak/data
      - teaspeak_config:/teaspeak/config
      - teaspeak_logs:/teaspeak/logs
      - teaspeak_files:/teaspeak/files
      - teaspeak_certs:/teaspeak/certs
    environment:
      - VOICE_PORT=9987
      - QUERY_PORT=10101
      - FILE_PORT=30303
    network_mode: "bridge"

volumes:
  teaspeak_data:
  teaspeak_config:
  teaspeak_logs:
  teaspeak_files:
  teaspeak_certs: