services:
  teaspeak-server:
    build: 
      context: .
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "9987:9987/udp"
      - "9987:9987/tcp"
      - "10101:10101/tcp"
      - "30303:30303/tcp"
    volumes:
      - type: volume
        source: teaspeak_certs
        target: /teaspeak/certs
      - type: volume
        source: teaspeak_config
        target: /teaspeak/config
      - type: volume
        source: teaspeak_db
        target: /teaspeak/database
      - type: volume
        source: teaspeak_files
        target: /teaspeak/files
      - type: volume
        source: teaspeak_logs
        target: /teaspeak/logs
      - type: volume
        source: teaspeak_crash_dumps
        target: /teaspeak/crash_dumps
    restart: unless-stopped

volumes:
  teaspeak_certs:
  teaspeak_crash_dumps:
  teaspeak_config:
  teaspeak_db:
  teaspeak_files:
  teaspeak_logs: