services:
  teaspeak1:
    build: .
    restart: always 
    environment:
      - VOICE_PORT=9987
      - QUERY_PORT=10101
      - FILE_PORT=30303
    ports:
      - "9987:9987/udp"
      - "10101:10101"
      - "30303:30303"
    volumes:
      - ./persistence/teaspeak1/data:/teaspeak/data
      - ./persistence/teaspeak1/config:/teaspeak/config
      - ./persistence/teaspeak1/logs:/teaspeak/logs

  teaspeak2:
    build: .
    restart: always 
    environment:
      - VOICE_PORT=9988
      - QUERY_PORT=10102
      - FILE_PORT=30304
    ports:
      - "9988:9987/udp"
      - "10102:10101"
      - "30304:30303"
    volumes:
      - ./persistence/teaspeak2/data:/teaspeak/data
      - ./persistence/teaspeak2/config:/teaspeak/config
      - ./persistence/teaspeak2/logs:/teaspeak/logs