[volume.logs]
path = "/ts/logs"

[volume.certs]
path = "/ts/certs"

[volume.config]
path = "/ts/config"

[volume.files]
path = "/ts/files"

[volume.database]
path = "/ts/database"

[volume.crash_dumps]
path = "/ts/crash_dumps"

[build]
builder = "docker"

[deploy]
startCommand = "./TeaSpeakServer -Pgeneral.database.url=sqlite://database/TeaData.sqlite"